name: v1be
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.12+13

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.5.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  share_plus: ^10.0.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  url_launcher: ^6.3.1
  rxdart: ^0.27.7
  provider: ^6.1.1
  in_app_purchase: ^3.2.0
  screenshot: ^3.0.0
  path_provider: ^2.1.2
  flutter_linkify: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.11

flutter:
  uses-material-design: true
